name = "icp-query"
type = "javascript"
account_id = "3f3f7b6b86669a040fcfbf088dc613ae"
workers_dev = true

[[kv_namespaces]]
binding = "cache"
preview_id = "6326f8f6a09b4c328bef795a284b97d3"
id = "c435166f0b3149c79a1b63f2822a65b7"

[triggers]
crons = ["* * * * *"]

[build]
watch_dir = "dist"

[build.upload]
format = "service-worker"
